import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData }) {
  return (
    <>
      <div className="">
        <Head>
          <title>Airbnb</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Banner />
        <main className="max-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-6">
            <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
            {/* Pull some data from a server - API endpoints - Static Rendering */}
            {exploreData?.map(({ img, distance, location }, ind) => (
              <SmallCard
                key={ind}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </section>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  return {
    props: {
      exploreData,
    },
  };
}
